---
# Handlers for bird

- name: restart bird
  service: name=bird state=restarted

- name: restart opencontrail-anycast-vip
  service: name=opencontrail-anycast-vip state=restarted

- name: restart haproxy
  service: name=haproxy state=restarted
